### ISSUE TITLE
Frage 1 keine Reaktion auf Eingabe "Alles"

### ISSUE THREAD

**Issue by admiraldeathrain** [admiraldeathrain/Askki#1]
Auf der ersten Fragenebene gibt es keine Reaktion auf die häufige Antwort "alles".

**Comment by oliverbregar** [comment]
Vorläufiger Text: Das ist dann doch stark übertrieben. Zum Teil bin ich tatsächlich KI, allerdings bin ich in meiner Funktion stark eingeschränkt. Wo glaubst du liegen diese Beschränkungen?

**Comment by admiraldeathrain** [comment]
In der Live-Version
