### ISSUE TITLE
Keine Rückmeldung des Bots nach seiner Anfrage "Versuche etwas anderes"

### ISSUE THREAD

**Issue by eugenbors** [admiraldeathrain/Askki#11]
Nach meiner Antwort "Du sprichst mit mir" und der Anfrage des Chatbots, man solle etwas anderes versuchen, antwortet er nicht mehr.
![image](https://user-images.githubusercontent.com/50580602/57619485-51cd7e80-7586-11e9-844f-6f92b6e2f6e9.png)

**Comment by admiraldeathrain** [comment]
Im nächsten Update behoben

**Comment by ThePorg** [comment]
Resolved in new Version
