### ISSUE TITLE
Gespräche enden, weil Chatbot nicht mehr reagiert

### ISSUE THREAD

**Issue by carolinehintermayr** [admiraldeathrain/Askki#12]
Meine Gespräche enden alle nach 3-4 Antworten, weil der Chatbot nicht mehr antwortet.

**Comment by admiraldeathrain** [comment]
Wie sehen die Antworten aus, nach denen nichts mehr kommt?

**Comment by carolinehintermayr** [comment]
Grundsätzlich bei, egal was ich antworte oder wenn ich wieder versuche aufs Ursprungsthema zu kommen: (oder ist das so gewollt?)
"Jetzt hast du mich erwischt. Ich bin darin beschränkt, dass ich nur Antworten geben kann, die mir zuvor eingegeben wurden. Für deine Aussage habe ich leider nur diese und keine bessere . . . Aber auch andere KI-Anwendungen sind beschränkt. Über welche davon würdest du gerne mehr erfahren?
Hier beginnt ab dem 24. 05. Akt 2"

Ansonsten war das grade, wenn ich mehrmals die gleiche Antwort gegeben habe (zb Ich weiß nicht). Aber jetzt funktioniert es

**Comment by admiraldeathrain** [comment]
Ah ja, das ist von der aktuellen Version der Endpunkt, danach wird der Bot in den nächsten Themenbereich leiten, das ist also so gedacht.
